-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.device
(
    id integer NOT NULL,
    user_id integer,
    status boolean DEFAULT false,
    last_seen timestamp without time zone,
    CONSTRAINT device_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.device_vehicle
(
    id serial NOT NULL,
    device_id integer NOT NULL,
    last_vin_id integer,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT device_vehicle_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.driving_events
(
    id serial NOT NULL,
    device_id integer NOT NULL,
    vehicle_id integer,
    event_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    event_timestamp timestamp without time zone NOT NULL,
    speed_kmh double precision,
    g_force double precision,
    accel_x double precision,
    accel_y double precision,
    accel_z double precision,
    gyro_x double precision,
    gyro_y double precision,
    gyro_z double precision,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    latitude double precision,
    longitude double precision,
    CONSTRAINT driving_events_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.dtc_codes_active
(
    id serial NOT NULL,
    vin_id integer NOT NULL,
    dtc_code character varying(20) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    severity character varying(20) COLLATE pg_catalog."default" DEFAULT 'medium'::character varying,
    CONSTRAINT dtc_codes_active_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.dtc_codes_history
(
    id serial NOT NULL,
    vin_id integer NOT NULL,
    dtc_code character varying(20) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    severity character varying(20) COLLATE pg_catalog."default" DEFAULT 'medium'::character varying,
    CONSTRAINT dtc_codes_history_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.dtc_codes_meaning
(
    id serial NOT NULL,
    dtc_code character varying(20) COLLATE pg_catalog."default" NOT NULL,
    dtc_description text COLLATE pg_catalog."default",
    CONSTRAINT dtc_codes_meaning_pkey PRIMARY KEY (id),
    CONSTRAINT dtc_codes_dtc_code_key UNIQUE (dtc_code),
    CONSTRAINT dtc_codes_meaning_dtc_code_key UNIQUE (dtc_code)
);

CREATE TABLE IF NOT EXISTS public.dtc_pattern_links
(
    id serial NOT NULL,
    pattern_id integer NOT NULL,
    dtc_code text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT dtc_pattern_links_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.dtc_patterns
(
    id serial NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    primary_cause text COLLATE pg_catalog."default" NOT NULL,
    source_url text COLLATE pg_catalog."default",
    CONSTRAINT dtc_patterns_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.pending_commands
(
    id serial NOT NULL,
    device_id integer NOT NULL,
    command character varying(50) COLLATE pg_catalog."default" NOT NULL,
    executed boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pending_commands_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.trips
(
    id serial NOT NULL,
    vehicle_id integer NOT NULL,
    start_time timestamp without time zone NOT NULL,
    end_time timestamp without time zone,
    duration_seconds integer,
    samples_count integer DEFAULT 0,
    start_odometer integer,
    end_odometer integer,
    distance_km double precision,
    avg_speed double precision,
    max_speed integer,
    avg_rpm double precision,
    max_rpm integer,
    min_rpm integer,
    avg_consumption_l100km double precision,
    total_fuel_used_l double precision,
    avg_coolant_temp double precision,
    max_coolant_temp integer,
    avg_oil_temp double precision,
    max_oil_temp integer,
    engine_starts integer DEFAULT 1,
    is_completed boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT trips_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.user_vehicles
(
    id serial NOT NULL,
    user_id integer NOT NULL,
    vehicle_id integer NOT NULL,
    CONSTRAINT user_vehicles_pkey PRIMARY KEY (id),
    CONSTRAINT unique_user_vehicle UNIQUE (user_id, vehicle_id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id serial NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    role character varying(50) COLLATE pg_catalog."default" DEFAULT 'user'::character varying,
    email character varying(120) COLLATE pg_catalog."default" NOT NULL,
    username character varying(80) COLLATE pg_catalog."default",
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.vehicle_location_history
(
    id serial NOT NULL,
    vehicle_id integer NOT NULL,
    trip_id integer,
    latitude double precision NOT NULL,
    longitude double precision NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT vehicle_location_history_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.vehicle_telemetry_history
(
    id serial NOT NULL,
    vehicle_id integer NOT NULL,
    odometer integer,
    battery_voltage double precision,
    battery_health character varying(30) COLLATE pg_catalog."default",
    engine_running boolean,
    engine_rpm integer,
    engine_load double precision,
    coolant_temp integer,
    oil_temp integer,
    intake_air_temp integer,
    consumption_lh double precision,
    consumption_l100km double precision,
    maf double precision,
    fuel_type character varying(20) COLLATE pg_catalog."default",
    speed integer,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    trip_id integer,
    odometer_source character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'rpi'::character varying,
    CONSTRAINT vehicle_telemetry_history_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.vehicle_telemetry_live
(
    id serial NOT NULL,
    vehicle_id integer NOT NULL,
    odometer integer,
    battery_voltage double precision,
    battery_health character varying(30) COLLATE pg_catalog."default",
    engine_running boolean,
    engine_rpm integer,
    engine_load double precision,
    coolant_temp integer,
    oil_temp integer,
    intake_air_temp integer,
    consumption_lh double precision,
    consumption_l100km double precision,
    maf double precision,
    fuel_type character varying(20) COLLATE pg_catalog."default",
    speed integer,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    odometer_source character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'rpi'::character varying,
    CONSTRAINT vehicle_telemetry_live_pkey PRIMARY KEY (id),
    CONSTRAINT unique_vehicle_live UNIQUE (vehicle_id)
);

CREATE TABLE IF NOT EXISTS public.vehicles
(
    id serial NOT NULL,
    vin character varying(50) COLLATE pg_catalog."default" NOT NULL,
    year character varying(10) COLLATE pg_catalog."default",
    model character varying(100) COLLATE pg_catalog."default",
    engine character varying(100) COLLATE pg_catalog."default",
    brand character varying(10) COLLATE pg_catalog."default",
    CONSTRAINT vehicles_pkey PRIMARY KEY (id),
    CONSTRAINT vehicles_vin_key UNIQUE (vin)
);

ALTER TABLE IF EXISTS public.device
    ADD CONSTRAINT device_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.device_vehicle
    ADD CONSTRAINT device_vehicle_device_id_fkey FOREIGN KEY (device_id)
    REFERENCES public.device (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_device_vehicle_device_id
    ON public.device_vehicle(device_id);


ALTER TABLE IF EXISTS public.device_vehicle
    ADD CONSTRAINT device_vehicle_last_vin_id_fkey FOREIGN KEY (last_vin_id)
    REFERENCES public.vehicles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.driving_events
    ADD CONSTRAINT fk_driving_events_device FOREIGN KEY (device_id)
    REFERENCES public.device (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_driving_events_device_id
    ON public.driving_events(device_id);


ALTER TABLE IF EXISTS public.driving_events
    ADD CONSTRAINT fk_driving_events_vehicle FOREIGN KEY (vehicle_id)
    REFERENCES public.vehicles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_driving_events_vehicle_id
    ON public.driving_events(vehicle_id);


ALTER TABLE IF EXISTS public.dtc_codes_active
    ADD CONSTRAINT dtc_codes_active_vin_id_fkey FOREIGN KEY (vin_id)
    REFERENCES public.vehicles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_dtc_active_vin_id
    ON public.dtc_codes_active(vin_id);


ALTER TABLE IF EXISTS public.dtc_codes_history
    ADD CONSTRAINT dtc_codes_history_vin_id_fkey FOREIGN KEY (vin_id)
    REFERENCES public.vehicles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_dtc_history_vin_id
    ON public.dtc_codes_history(vin_id);


ALTER TABLE IF EXISTS public.dtc_pattern_links
    ADD CONSTRAINT dtc_pattern_links_pattern_id_fkey FOREIGN KEY (pattern_id)
    REFERENCES public.dtc_patterns (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_pattern_links_pattern
    ON public.dtc_pattern_links(pattern_id);


ALTER TABLE IF EXISTS public.pending_commands
    ADD CONSTRAINT pending_commands_device_id_fkey FOREIGN KEY (device_id)
    REFERENCES public.device (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_pending_commands_device_id
    ON public.pending_commands(device_id);


ALTER TABLE IF EXISTS public.trips
    ADD CONSTRAINT trips_vehicle_id_fkey FOREIGN KEY (vehicle_id)
    REFERENCES public.vehicles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_trips_vehicle_id
    ON public.trips(vehicle_id);


ALTER TABLE IF EXISTS public.user_vehicles
    ADD CONSTRAINT user_vehicles_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_user_vehicles_user_id
    ON public.user_vehicles(user_id);


ALTER TABLE IF EXISTS public.user_vehicles
    ADD CONSTRAINT user_vehicles_vehicle_id_fkey FOREIGN KEY (vehicle_id)
    REFERENCES public.vehicles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_user_vehicles_vehicle_id
    ON public.user_vehicles(vehicle_id);


ALTER TABLE IF EXISTS public.vehicle_location_history
    ADD CONSTRAINT vehicle_location_history_trip_id_fkey FOREIGN KEY (trip_id)
    REFERENCES public.trips (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_vehicle_location_history_trip_id
    ON public.vehicle_location_history(trip_id);


ALTER TABLE IF EXISTS public.vehicle_location_history
    ADD CONSTRAINT vehicle_location_history_vehicle_id_fkey FOREIGN KEY (vehicle_id)
    REFERENCES public.vehicles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_vehicle_location_history_vehicle_id
    ON public.vehicle_location_history(vehicle_id);


ALTER TABLE IF EXISTS public.vehicle_telemetry_history
    ADD CONSTRAINT vehicle_telemetry_history_trip_id_fkey FOREIGN KEY (trip_id)
    REFERENCES public.trips (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_vehicle_history_trip_id
    ON public.vehicle_telemetry_history(trip_id);


ALTER TABLE IF EXISTS public.vehicle_telemetry_history
    ADD CONSTRAINT vehicle_telemetry_history_vehicle_id_fkey FOREIGN KEY (vehicle_id)
    REFERENCES public.vehicles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_vehicle_history_vehicle_id
    ON public.vehicle_telemetry_history(vehicle_id);


ALTER TABLE IF EXISTS public.vehicle_telemetry_live
    ADD CONSTRAINT vehicle_telemetry_live_vehicle_id_fkey FOREIGN KEY (vehicle_id)
    REFERENCES public.vehicles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS unique_vehicle_live
    ON public.vehicle_telemetry_live(vehicle_id);

END;